export default {

	//CONSTANTS ACTION FOR CONFIGURATION
	ADD_NEW_DRINK: 'ADD_NEW_DRINK',
	ADD_NEW_PRICES: 'ADD_NEW_PRICES',
	SET_NUMBER_OF_DRINKS: 'SET_NUMBER_OF_DRINKS',
	SET_REFRESHING_TIME_INTERVAL: 'SET_REFRESHINGs_TIME_INTERVAL',

	//CONSTANTS ACTION FOR CHART
	SET_NEW_PRICES: 'SET_NEW_PRICES'
}